# This is a basic workflow to help you get started with Actions

name: Python application test with Github Actions   


# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python 3.8
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

      # Runs a single command using the runners shell
    - name: Install dependecies
      run: |
        make install

      # Runs a set of commands using the runners shell
    - name: Format code with python black
      run: |
        make format
    - name: lint with pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
